#ifndef __LIBMONSTA_PLATFORM_VERSION_H__
#define __LIBMONSTA_PLATFORM_VERSION_H__

#define LIB_MONSTA_VERSION "0.0.1"
#define LIB_MONSTA_OPENGL_MAJOR 3
#define LIB_MONSTA_OPENGL_MINOR 3

#endif /* __LIBMONSTA_PLATFORM_VERSION_H__ */